-- Таблица клиентов с JSON-полем для метаданных (Oracle 21c/23ai style)
CREATE TABLE customers (
    customer_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50) NOT NULL,
    last_name      VARCHAR2(50) NOT NULL,
    email          VARCHAR2(100) UNIQUE NOT NULL,
    phone          VARCHAR2(20),
    preferences    JSON, -- Храним настройки уведомлений, любимые категории
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица товаров
CREATE TABLE products (
    product_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(200) NOT NULL,
    sku            VARCHAR2(50) UNIQUE NOT NULL,
    price          NUMBER(10, 2) NOT NULL CHECK (price >= 0),
    stock_quantity NUMBER DEFAULT 0,
    category       VARCHAR2(100)
);

-- Таблица заказов
CREATE TABLE orders (
    order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    NUMBER NOT NULL,
    order_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status         VARCHAR2(20) DEFAULT 'NEW',
    total_amount   NUMBER(15, 2) DEFAULT 0,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT chk_status CHECK (status IN ('NEW', 'PAID', 'SHIPPED', 'CANCELLED'))
);

-- Состав заказа (Многие-ко-многим)
CREATE TABLE order_items (
    order_id       NUMBER NOT NULL,
    product_id     NUMBER NOT NULL,
    quantity       NUMBER NOT NULL CHECK (quantity > 0),
    unit_price     NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);
