CREATE TABLE price_history (
    history_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   NUMBER NOT NULL,
    old_price    NUMBER(10, 2),
    new_price    NUMBER(10, 2),
    change_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed_by   VARCHAR2(100), -- Имя пользователя БД
    CONSTRAINT fk_history_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);
