-- Пересоздаем таблицу заказов с секционированием по диапазону дат
CREATE TABLE orders_hist (
    order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id  NUMBER NOT NULL,
    order_date   DATE DEFAULT SYSDATE,
    status       VARCHAR2(20),
    total_amount NUMBER(15,2)
)
PARTITION BY RANGE (order_date) (
    PARTITION p_2023 VALUES LESS THAN (TO_DATE('01-01-2024', 'DD-MM-YYYY')),
    PARTITION p_2024 VALUES LESS THAN (TO_DATE('01-01-2025', 'DD-MM-YYYY')),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);
